### ISSUE TITLE
Винести кнопки перемикання слайдів поза контейнер, щоб не накладались на слайди

### ISSUE THREAD

**Issue by skorovDev** [skorovDev/test_landing_product#3]
![image](https://user-images.githubusercontent.com/98920475/152512813-5309435d-c8a6-4e38-a076-fe4e55f1e31f.png)

![image](https://user-images.githubusercontent.com/98920475/152512892-d784e57a-9e48-4374-b1de-d04f147c510d.png)

**Comment by Tkachyshyn-Andrei** [comment]
[fix prev-next-button position](https://github.com/skorovDev/test_landing_product/commit/3560ef63b80fdd2407fb4d4c4030608999e49508)
